api-version: 1.16
name: RedVSBlue
version: 1.1
main: org.onlyvanilla.redvsblue.Main
description: Red VS Blue Commands
commands:
    rvbjoin:
        description: Join the event
        usage: /rvbjoin
    rvblist:
        description: List event players
        usage: /rvblistp
    rvbhelp:
        description: Get help page
        usage: /rvbhelp
    rvbstandings:
        description: See standings
        usage: /rvbstandings
    rvbtasks:
        description: See monthly tasks
        usage: /rvbtasks
    rvbprizes:
        description: See rvb prizes
        usage: /rvbprizes
    rvbrules:
        description: See rvb rules
        usage: /rvbrules
    rvbaddpoints:
        description: Add points to team
        usage: /rvbaddpoints [team] [points]
        permission: rvb.rvbaddpoints
